"""Generate config and .env for first run."""

from __future__ import annotations

import os
import secrets
import shutil
from pathlib import Path

import yaml


def ensure_layout(root: Path) -> None:
    for relative in (
        "config",
        "data/findings",
        "data/reference",
        "data/postgres",
        "data/forgejo",
        "data/forgejo-runner",
        "data/repos",
        "models",
        "logs/model-servers",
    ):
        (root / relative).mkdir(parents=True, exist_ok=True)


def generate_env(root: Path, *, force: bool = False, platform: dict | None = None) -> Path:
    path = root / ".env"
    repo_root_line = f"SHIFT_LEFT_REPO_ROOT={root.resolve()}"
    if path.exists() and not force:
        text = path.read_text()
        if "SHIFT_LEFT_REPO_ROOT=" not in text:
            path.write_text(text.rstrip() + "\n" + repo_root_line + "\n")
        return path

    hosting = (platform or {}).get("model_hosting", "host-native-macos")
    lines = [
        "# Generated by ./shift-left up — secrets stay here, not in shift-left.yaml",
        repo_root_line,
        f"POSTGRES_PASSWORD={secrets.token_urlsafe(24)}",
        f"FORGEJO_SECRET_KEY={secrets.token_urlsafe(32)}",
        f"FORGEJO_INTERNAL_TOKEN={secrets.token_urlsafe(32)}",
        f"FORGEJO_JWT_SECRET={secrets.token_urlsafe(32)}",
        f"FORGEJO_TOKEN=",
        f"FORGEJO_RUNNER_TOKEN=",
        "FORGEJO_ROOT_URL=http://localhost:3000",
        "FORGEJO_RUNNER_URL=http://forgejo:3000",
        "ORCHESTRATOR_PORT=8080",
        "FORGEJO_PORT=3000",
        "SHIFT_LEFT_SKIP_EGRESS_PROBE=1",
        f"SHIFT_LEFT_MODEL_HOSTING={hosting}",
        "ANTARES_SERVICE_URL=http://host.docker.internal:8090",
        "FOUNDATION_SEC_SERVICE_URL=http://host.docker.internal:8091",
        "SHIFT_LEFT_STATE_DIR=.shift-left",
        "",
    ]
    path.write_text("\n".join(lines))
    return path


def generate_config(root: Path, *, force: bool = False, platform: dict | None = None) -> Path:
    dest = root / "config" / "shift-left.yaml"
    if dest.is_dir():
        import shutil

        print("Config: replacing mistaken config/shift-left.yaml directory with file …")
        shutil.rmtree(dest)
    if dest.is_file() and not force:
        return dest

    example = root / "config" / "shift-left.example.yaml"
    if not example.exists():
        raise FileNotFoundError(f"Missing {example}")

    raw = yaml.safe_load(example.read_text())
    if not isinstance(raw, dict):
        raise ValueError("Invalid example config")

    fs = raw.setdefault("models", {}).setdefault("foundation_sec", {})
    from shift_left_cli.models_check import inspect_model_staging

    staging = inspect_model_staging(root)
    if staging.foundation_sec_q4_path is not None:
        fs["use_low_memory"] = True
    elif staging.foundation_sec_q8_path is not None:
        fs["use_low_memory"] = False
    else:
        fs["use_low_memory"] = True  # default Q4_K_M download profile
    fs["max_context_tokens"] = 4096
    fs["local_path_low_memory"] = "models/foundation-sec-q4_k_m"
    if not staging.use_low_memory:
        fs["local_path"] = "models/foundation-sec-q8_0"

    ant = raw.setdefault("models", {}).setdefault("antares", {})
    ant["enabled"] = False
    ant["installed"] = False

    triage = raw.setdefault("antares_triage", {})
    triage["installed"] = False

    raw.setdefault("findings_store", {})["sqlite_path"] = "data/findings/shift-left.db"
    raw.setdefault("reference_data", {})["cache_dir"] = "data/reference"

    if platform:
        raw.setdefault("_shift_left_detected", platform)

    gate = raw.setdefault("gate", {})
    from shift_left_cli.forgejo_bootstrap import _read_bootstrap_secret
    from shift_left_cli.sample_repo import SAMPLE_REPO_NAME

    sample_owner = _read_bootstrap_secret(root, "forgejo_admin_user") or "shift-left"
    gate["check_repo"] = f"{sample_owner}/{SAMPLE_REPO_NAME}"
    gate["warn_if_branch_protection_missing"] = False

    orch = raw.setdefault("orchestrator", {})
    orch["host"] = "0.0.0.0"
    orch["port"] = int(os.environ.get("ORCHESTRATOR_PORT", "8080"))

    # Docker publishes orchestrator to the host; clients arrive as bridge IPs, not 127.0.0.1.
    ui = raw.setdefault("ui", {})
    ui["allow_remote_view"] = True

    dest.write_text(yaml.safe_dump(raw, sort_keys=False))
    manifest_example = root / "config" / "prewarm-manifest.example.json"
    manifest_dest = root / "models" / ".prewarm-manifest.json"
    if manifest_example.exists() and not manifest_dest.exists():
        shutil.copy(manifest_example, manifest_dest)

    if staging.foundation_sec_q8_path and not staging.foundation_sec_q4_path:
        print("Config: using Foundation-Sec Q8_0 (Q4_K_M not staged).")

    from shift_left_cli.forgejo_config import ensure_forgejo_app_config

    if ensure_forgejo_app_config(root):
        print("Config: wrote Forgejo app.ini (headless install, INSTALL_LOCK=true).")

    return dest


def copy_prewarm_manifest(root: Path) -> None:
    example = root / "config" / "prewarm-manifest.example.json"
    dest = root / "models" / ".prewarm-manifest.json"
    if example.exists() and not dest.exists():
        shutil.copy(example, dest)
