"""Generate Forgejo app.ini for headless Docker bootstrap (no web install wizard)."""

from __future__ import annotations

import os
import secrets
import subprocess
from pathlib import Path


def ensure_forgejo_app_config(root: Path) -> bool:
    """
    Write data/forgejo/custom/conf/app.ini with INSTALL_LOCK=true and secrets from .env.

    Returns True when the file changed (caller should restart the forgejo container).
    """
    from shift_left_cli.up import load_dotenv

    load_dotenv(root)
    env_path = root / ".env"
    env = _read_env(env_path)
    env_changed = _ensure_forgejo_env_secrets(env)
    if env_changed:
        _sync_env_file(env_path, env)

    dest = root / "data" / "forgejo" / "custom" / "conf" / "app.ini"
    dest.parent.mkdir(parents=True, exist_ok=True)
    content = _render_app_ini(env)
    if dest.exists():
        existing = dest.read_text()
        if "INSTALL_LOCK = true" in existing and _postgres_password_in_ini(existing, env):
            return False
        if existing == content:
            return False
    dest.write_text(content)
    return True


def ensure_forgejo_data_permissions(root: Path) -> None:
    """Align data/forgejo ownership with rootless Forgejo (UID/GID 1000 in the official image)."""
    data = root / "data" / "forgejo"
    data.mkdir(parents=True, exist_ok=True)
    cleanup_stale_forgejo_run_containers(root)
    from shift_left_cli.compose_util import detect_compose

    compose = detect_compose(root)
    subprocess.run(
        compose.cmd(
            "run",
            "--rm",
            "--no-deps",
            "--user",
            "root",
            "--entrypoint",
            "chown",
            "forgejo",
            "-R",
            "1000:1000",
            "/var/lib/gitea",
        ),
        cwd=root,
        capture_output=True,
        check=False,
    )


def cleanup_stale_forgejo_run_containers(root: Path) -> None:
    """Stop orphaned ``docker compose run forgejo`` containers that hold queue DB locks."""
    project = os.environ.get("COMPOSE_PROJECT_NAME", "shift-left")
    result = subprocess.run(
        [
            "docker",
            "ps",
            "-q",
            "--filter",
            f"name={project}-forgejo-run-",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    for container_id in result.stdout.split():
        subprocess.run(["docker", "stop", container_id.strip()], capture_output=True, check=False)


def _postgres_password_in_ini(ini_text: str, env: dict[str, str]) -> bool:
    expected = env.get("POSTGRES_PASSWORD", "")
    if not expected:
        return False
    for line in ini_text.splitlines():
        if line.strip().startswith("PASSWD ="):
            return line.split("=", 1)[1].strip() == expected
    return False


def _read_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    env: dict[str, str] = {}
    for line in path.read_text().splitlines():
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        env[key.strip()] = value.strip()
    return env


def _write_env(path: Path, env: dict[str, str]) -> None:
    lines = ["# Generated by ./shift-left up — secrets stay here, not in shift-left.yaml"]
    for key, value in env.items():
        lines.append(f"{key}={value}")
    path.write_text("\n".join(lines) + "\n")


def _ensure_forgejo_env_secrets(env: dict[str, str]) -> bool:
    changed = False
    if not env.get("POSTGRES_PASSWORD"):
        env["POSTGRES_PASSWORD"] = secrets.token_urlsafe(24)
        changed = True
    for key in ("FORGEJO_SECRET_KEY", "FORGEJO_INTERNAL_TOKEN", "FORGEJO_JWT_SECRET"):
        if not env.get(key):
            env[key] = secrets.token_urlsafe(32)
            changed = True
    return changed


def _sync_env_file(path: Path, env: dict[str, str]) -> None:
    """Append missing Forgejo keys without rewriting existing .env lines."""
    if not path.exists():
        _write_env(path, env)
        return
    lines = path.read_text().splitlines()
    present = _read_env(path)
    appended: list[str] = []
    for key, value in env.items():
        if key not in present or not present[key]:
            lines.append(f"{key}={value}")
            appended.append(key)
    if appended:
        path.write_text("\n".join(lines) + "\n")


def _render_app_ini(env: dict[str, str]) -> str:
    postgres_password = env.get("POSTGRES_PASSWORD", "forgejo-dev-only")
    secret_key = env.get("FORGEJO_SECRET_KEY", secrets.token_urlsafe(32))
    internal_token = env.get("FORGEJO_INTERNAL_TOKEN", secrets.token_urlsafe(32))
    jwt_secret = env.get("FORGEJO_JWT_SECRET", secrets.token_urlsafe(32))
    root_url = env.get("FORGEJO_ROOT_URL", "http://localhost:3000").rstrip("/") + "/"

    return f"""APP_NAME = Shift-Left
RUN_USER = git

[server]
DOMAIN = localhost
HTTP_PORT = 3000
ROOT_URL = {root_url}
APP_DATA_PATH = /var/lib/gitea/data
DISABLE_SSH = false
SSH_PORT = 2222
LFS_START_SERVER = false
OFFLINE_MODE = true

[database]
DB_TYPE = postgres
HOST = postgres:5432
NAME = forgejo
USER = forgejo
PASSWD = {postgres_password}
SSL_MODE = disable

[repository]
ROOT = /var/lib/gitea/git/repositories

[security]
INSTALL_LOCK = true
SECRET_KEY = {secret_key}
INTERNAL_TOKEN = {internal_token}

[oauth2]
JWT_SECRET = {jwt_secret}

[service]
DISABLE_REGISTRATION = false
REQUIRE_SIGNIN_VIEW = false
DEFAULT_KEEP_EMAIL_PRIVATE = true
DEFAULT_ALLOW_CREATE_ORGANIZATION = true

[actions]
ENABLED = true
DEFAULT_ACTIONS_URL = https://code.forgejo.org

[log]
MODE = console
LEVEL = Info

[ui]
DEFAULT_THEME = forgejo-auto
"""


def sync_postgres_password(root: Path) -> None:
    """Align the forgejo role password with .env (Postgres only reads POSTGRES_PASSWORD on first init)."""
    from shift_left_cli.compose_util import detect_compose
    from shift_left_cli.up import load_dotenv

    load_dotenv(root)
    password = os.environ.get("POSTGRES_PASSWORD", "").strip()
    if not password:
        return

    escaped = password.replace("'", "''")
    sql = f"ALTER USER forgejo WITH PASSWORD '{escaped}';"
    compose = detect_compose(root)
    result = subprocess.run(
        compose.cmd(
            "exec",
            "-T",
            "postgres",
            "psql",
            "-U",
            "forgejo",
            "-d",
            "forgejo",
            "-v",
            "ON_ERROR_STOP=1",
            "-c",
            sql,
        ),
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        detail = (result.stderr or result.stdout or "").strip()
        raise RuntimeError(f"Could not sync Postgres password for Forgejo: {detail or result.returncode}")
