#!/usr/bin/env python3
"""Generate public docs from code.

Writes:
  docs/openapi.yaml
  docs/openapi.json
  docs/configuration-reference.md
  docs/supported-platforms.md

OpenAPI is generated by scripts/generate-openapi.py (also `make docs-openapi`).

Refresh::

    PYTHONPATH=services/orchestrator:services/shift-left-shared \\
      .venv/bin/python scripts/generate_docs.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, get_args, get_origin

ROOT = Path(__file__).resolve().parents[1]
ORCH = ROOT / "services" / "orchestrator"
SHARED = ROOT / "services" / "shift-left-shared"
for path in (ORCH, SHARED):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

# Repo-relative vs rewritten at load time. See config._resolve_storage_path.
PATH_KIND: dict[str, str] = {
    "reference_data.cache_dir": "repo-relative (`data/...`); Compose remaps via SHIFT_LEFT_DATA_DIR=/data",
    "antares_triage.repos_checkout_dir": "repo-relative (`data/repos`); Compose remaps via SHIFT_LEFT_DATA_DIR",
    "investigations.sqlite_path": "repo-relative sqlite; Compose remaps via SHIFT_LEFT_DATA_DIR",
    "findings_store.sqlite_path": "repo-relative sqlite; Compose remaps via SHIFT_LEFT_DATA_DIR",
    "audit.sqlite_path": "repo-relative sqlite (defaults beside findings store); Compose remaps via SHIFT_LEFT_DATA_DIR",
    "auth.sqlite_path": "repo-relative sqlite (defaults beside findings store); Compose remaps via SHIFT_LEFT_DATA_DIR",
    "models.antares.local_path": "repo-relative under models/; host-native server reads the Mac path",
    "models.foundation_sec.local_path": "repo-relative under models/",
    "models.foundation_sec.local_path_low_memory": "repo-relative under models/",
    "models.foundation_sec.local_path_reasoning": "repo-relative under models/",
    "models.antares.service_url": "URL. Compose default is the service hostname; macOS host-native uses http://host.docker.internal:8090",
    "models.foundation_sec.service_url": "URL. Compose default is the service hostname; macOS host-native uses http://host.docker.internal:8091",
    "git.bundled.url": "URL. Inside Compose use http://forgejo:3000; from the host use http://127.0.0.1:3000",
    "deployment.fmc.terraform_workdir": "repo-relative directory",
}

RESTART: dict[str, str] = {
    "schema_version": "load-time; mismatch refuses to start",
    "distribution.auto_update": "startup rejects true",
    "distribution.telemetry": "startup rejects true",
    "sovereignty.deny_egress": "orchestrator restart",
    "git": "orchestrator restart",
    "routing": "orchestrator restart",
    "policy": "orchestrator restart (GET /api/v1/policy says YAML edit + restart)",
    "gate": "orchestrator restart",
    "advisory_suppression": "orchestrator restart",
    "orchestrator": "orchestrator restart",
    "ui": "orchestrator restart",
    "models.antares.local_path": "antares-server restart",
    "models.antares.service_url": "orchestrator restart",
    "models.antares.enabled": "orchestrator restart",
    "models.foundation_sec.local_path": "foundation-sec-server restart",
    "models.foundation_sec.use_low_memory": "foundation-sec-server restart (also writable via system settings API, then restart models)",
    "models.foundation_sec.service_url": "orchestrator restart",
    "findings_store.sqlite_path": "orchestrator restart",
    "antares_triage.repos_checkout_dir": "orchestrator restart (must stay on the data volume)",
    "rbac.allow_self_approval": "hot via PATCH /api/v1/system/settings/rbac/allow-self-approval",
}

PLATFORM_ORDER = (
    "cisco_secure_firewall",
    "cisco_ftd",
    "cisco_ios_xe",
    "cisco_nx_os",
    "generic_terraform",
)

PLATFORM_PROSE: dict[str, dict[str, str]] = {
    "cisco_secure_firewall": {
        "title": "Cisco ASA (`cisco_secure_firewall`)",
        "extensions": "`**/*.rules`, `**/*.conf`",
        "understands": (
            "Named and numbered ACLs (`access-list` ACE lines), `object` / `object-group` "
            "network and service definitions (including nested `group-object`), "
            "`ssh` / `http` / `telnet` management access, and crypto map / IKEv1-IKEv2 blocks "
            "used by ASA-004."
        ),
        "resolve": (
            "Object and object-group references resolve before any rule runs (depth cap 16, "
            "circular-reference detection). ACE source, destination, and service are judged on "
            "effective values, not on the literal `object-group` token. Unresolved or circular "
            "references are never assumed narrow."
        ),
        "unparsed": (
            "ACL-bearing lines the tokenizer cannot represent, and ACE references to undefined "
            "object-groups, emit **ASA-007** (CWE-754, block). Standard ACL one-liners that are "
            "not extended ACE form are unparsed. A `.cfg` file on an ASA target is **not** in "
            "parser scope — it is unclaimed (CWE-657), not ASA-007."
        ),
        "not_parsed": (
            "IOS-XE / NX-OS CLI, FMC Terraform, and any path outside `*.rules` / `*.conf`. "
            "ASA-003 (permit without logging) exists in the registry as disabled."
        ),
    },
    "cisco_ftd": {
        "title": "Cisco FMC / FTD Terraform (`cisco_ftd`)",
        "extensions": "`**/*.tf`, `**/*.hcl`",
        "understands": (
            "CiscoDevNet/fmc provider **2.0.1** resources: `fmc_access_rule`, bulk "
            "`fmc_access_rules` items, `fmc_port` / network objects, and IKEv2 policy. "
            "Network literals use assignment form (`source_network_literals = [{ value = \"...\" }]`). "
            "`access_control_policy_id` is a literal ID string in corpus fixtures — "
            "`fmc_access_policy` is not a 2.0.1 resource."
        ),
        "resolve": (
            "Network and port object references on a rule resolve through the FMC symbol table "
            "before FTD-001 / FTD-005 / FTD-006 run. An unconstrained endpoint (no literals and "
            "no object refs) is treated as exposed for FTD-005 and **not** as catch-all for FTD-006. "
            "See [gate-enforcement.md](gate-enforcement.md)."
        ),
        "unparsed": (
            "If `python-hcl2` is missing or `hcl2.loads()` fails, **HCL-001** (CWE-754, block) "
            "fires and no FTD rule runs. Dangling object refs emit **FTD-008**. Uncovered non-`fmc_` "
            "provider prefixes emit **FTD-009** (flag), not a silent pass."
        ),
        "not_parsed": (
            "Live FMC API state, FTD CLI, ASA `access-list` text, and Terraform resources whose "
            "provider prefix is not `fmc_` (those are FTD-009 coverage gaps). FTD-007 (intrusion "
            "policy omitted) is disabled in the registry."
        ),
    },
    "cisco_ios_xe": {
        "title": "Cisco IOS-XE (`cisco_ios_xe`)",
        "extensions": "`**/*.cfg`, `**/*.conf`, `**/*.txt` — `.cfg` is per-target only, not globally claimed",
        "understands": (
            "Global settings, `line` / VTY blocks, `interface` blocks, AAA, SNMP, management "
            "services (`ip ssh`, `transport input`), and standard/extended numbered and named ACLs "
            "as `AccessListEntry` with line numbers. Parser layout: `parsers/ios_xe/` "
            "(`parser.py`, `resolver.py`, `checks.py`)."
        ),
        "resolve": (
            "`object-group network` and `object-group service` are indexed including nested "
            "`group-object`. Resolution runs before rules (depth cap 16, circular detection). "
            "There is no literal-only evaluation path."
        ),
        "unparsed": (
            "UNPARSED ACL/config lines and UNRESOLVED object-group refs emit **IOS-001** (CWE-754, block). "
            "When the declared target type disagrees with sniffed IOS-XE / NX-OS / ASA markers, "
            "**IOS-010** fires (CWE-754, block). Neither declaration nor sniff is trusted silently."
        ),
        "not_parsed": (
            "NX-OS `ip access-list` block syntax (sniffed as NX-OS → IOS-010), ASA `access-list` "
            "extended form on an IOS-XE target, and `.cfg` files when no `cisco_ios_xe` managed "
            "target matches — those stay unclaimed (CWE-657) because `**/*.cfg` is omitted from "
            "global routing claim globs. IOS-009 (BPDU guard / port-security) is disabled."
        ),
    },
    "cisco_nx_os": {
        "title": "Cisco NX-OS (`cisco_nx_os`)",
        "extensions": "`**/*.cfg`, `**/*.conf`, `**/*.txt` — `.cfg` is per-target only",
        "understands": (
            "`ip access-list <name>` configuration **blocks** (sequence-numbered permit/deny), "
            "`object-group ip address` / `object-group ip port` with nesting, `feature`, `line`, "
            "`role`, and `vrf context` blocks covered by NXOS-003–NXOS-010."
        ),
        "resolve": (
            "Object-group members resolve with nesting and circular-reference detection before "
            "NXOS-003 (any-any) and related rules run. Unresolved groups emit NXOS-001."
        ),
        "unparsed": (
            "Standalone top-level `access-list …` one-liners (legacy numbered ACL syntax without "
            "a block header) are counted as ACL-bearing for parse-coverage metrics but stored as "
            "unparsed and emit **NXOS-001** (CWE-754, block) **by design**. They do not silently PASS. "
            "Declared vs sniffed platform mismatch emits **NXOS-002**."
        ),
        "not_parsed": (
            "IOS-XE CLI, ASA `access-list` extended form, and NX-OS features outside the blocks "
            "listed above. Rewrite standalone `access-list` lines as `ip access-list <name>` "
            "with sequence numbers, or accept NXOS-001 / waive with approve."
        ),
    },
    "generic_terraform": {
        "title": "Generic Terraform (`generic_terraform`)",
        "extensions": "`**/*.tf`, `**/*.hcl`, `**/*.tfvars`",
        "understands": (
            "HCL resource blocks parsed with `python-hcl2`. TF-001 evaluates internet-wide ingress "
            "on AWS / Azure / GCP security-group style resources. FMC resources in a generic_terraform "
            "target are handled as uncovered providers (HCL-002) unless they match TF-001."
        ),
        "resolve": (
            "No network object-group table. CIDRs and `0.0.0.0/0` are read from resource attributes. "
            "Provider prefix is taken from the resource type (`aws_`, `azurerm_`, `google_`, `fmc_`)."
        ),
        "unparsed": (
            "Missing `python-hcl2` or HCL syntax errors emit **HCL-001** (CWE-754, block) and stop. "
            "Successfully parsed files whose resource prefixes are outside the enabled rule set emit "
            "**HCL-002** (CWE-657, flag) so parseable-but-unevaluated providers cannot silent-pass."
        ),
        "not_parsed": (
            "Providers other than `aws_`, `azurerm_`, `google_`, and `fmc_` (HCL-002). "
            "FMC-specific FTD-00x checks do not run on `generic_terraform` — use target_type "
            "`cisco_ftd` for those. `.tfvars` is in parser scope; interpretability still requires "
            "valid HCL."
        ),
    },
}


def _type_name(annotation: Any) -> str:
    origin = get_origin(annotation)
    if origin is None:
        if hasattr(annotation, "__name__"):
            return annotation.__name__
        return str(annotation).replace("typing.", "")
    args = ", ".join(_type_name(arg) for arg in get_args(annotation) or ())
    origin_name = getattr(origin, "__name__", str(origin))
    if args:
        return f"{origin_name}[{args}]"
    return origin_name


def _default_repr(value: Any) -> str:
    if value is ...:
        return "*(required)*"
    try:
        from pydantic import BaseModel
        from pydantic_core import PydanticUndefined

        if value is PydanticUndefined:
            return "*(required)*"
        if isinstance(value, BaseModel):
            return "`{}` (nested defaults)"
    except Exception:
        pass
    text = json.dumps(value, default=str)
    if len(text) > 80:
        return "`" + text[:77] + "...`"
    return f"`{text}`"


def _walk_model(model: type, prefix: str = "") -> list[tuple[str, Any]]:
    from pydantic import BaseModel

    rows: list[tuple[str, Any]] = []
    for name, field in model.model_fields.items():
        key = f"{prefix}.{name}" if prefix else name
        annotation = field.annotation
        origin = get_origin(annotation)
        args = get_args(annotation)
        nested = None
        if isinstance(annotation, type) and issubclass(annotation, BaseModel) and annotation is not model:
            nested = annotation
        elif origin is None:
            nested = None
        else:
            for arg in args:
                if isinstance(arg, type) and issubclass(arg, BaseModel):
                    nested = arg
                    break
        rows.append((key, field))
        if nested is not None and name != "rules":
            rows.extend(_walk_model(nested, key))
    return rows


def _field_default(field: Any) -> str:
    factory = getattr(field, "default_factory", None)
    if factory is not None:
        try:
            return _default_repr(factory())
        except TypeError:
            return "`{}` (nested defaults)"
    return _default_repr(field.default)


def _restart_for(key: str) -> str:
    if key in RESTART:
        return RESTART[key]
    parts = key.split(".")
    for i in range(len(parts) - 1, 0, -1):
        parent = ".".join(parts[:i])
        if parent in RESTART:
            return RESTART[parent]
    return "orchestrator restart unless listed as hot-reload above"


def write_config_reference(path: Path) -> None:
    from shift_left.config import CURRENT_SCHEMA_VERSION, AppConfig

    rows = _walk_model(AppConfig)
    lines = [
        "# Configuration reference",
        "",
        "This is the generated catalog of `config/shift-left.yaml` keys for operators who need "
        "types, defaults, restart behavior, and whether a path is repo-relative or container-absolute.",
        "",
        f"Generated from the Pydantic models in `services/orchestrator/shift_left/config.py` "
        f"(schema_version **{CURRENT_SCHEMA_VERSION}**). Do not edit this file by hand.",
        "",
        "Regenerate:",
        "",
        "```bash",
        "PYTHONPATH=services/orchestrator:services/shift-left-shared \\",
        "  .venv/bin/python scripts/generate_docs.py --config-ref",
        "```",
        "",
        "Copy `config/shift-left.example.yaml` or let `./shift-left up` write `config/shift-left.yaml`. "
        "A missing or mismatched `schema_version` refuses to start:",
        "",
        "```",
        "unsupported schema_version N (expected 11).",
        "```",
        "",
        "YAML `data/...` paths are repo-relative. Inside Compose, `SHIFT_LEFT_DATA_DIR=/data` maps them "
        "onto the writable volumes (`./data/findings:/data/findings`, `./data/repos:/data/repos`). "
        "Legacy container-absolute values such as `/shift-left/data/repos` are rewritten at load; "
        "the rewrite is visible on the system page. Do not point sqlite or checkouts at `/shift-left/data` "
        "— that bind-mount is read-only.",
        "",
        "Operator-mutable model paths can also be changed from the system UI; quant and weight-path "
        "changes still require a model-server restart. Policy YAML is not hot-reloaded.",
        "",
        "| Key | Type | Default | Restart | Path |",
        "|-----|------|---------|---------|------|",
    ]
    for key, field in rows:
        if key == "legacy_path_rewrites":
            continue
        typ = _type_name(field.annotation)
        default = _field_default(field)
        restart = _restart_for(key)
        path_kind = PATH_KIND.get(key, "—")
        desc = (field.description or "").replace("\n", " ")
        extra = f" {desc}" if desc else ""
        lines.append(
            f"| `{key}` | `{typ}` | {default} | {restart} | {path_kind}{extra} |"
        )
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def _rules_for_platform(target_type: str):
    from shift_left.handlers.config.rules.registry import ALL_RULES

    rules = [rule for rule in ALL_RULES if rule.target_type == target_type]
    if target_type == "cisco_ftd":
        extra = [rule for rule in ALL_RULES if rule.id == "HCL-001"]
        ids = {rule.id for rule in rules}
        rules.extend(rule for rule in extra if rule.id not in ids)
    return rules


def write_supported_platforms(path: Path) -> None:
    from shift_left.handlers.config.parser_scope import TARGET_TYPE_PARSER_GLOBS

    lines = [
        "# Supported platforms",
        "",
        "This is the operator and contributor reference for the five config target types the "
        "deterministic gate can parse. Rule tables are generated from the registry; do not edit them by hand.",
        "",
        "Generated from `services/orchestrator/shift_left/handlers/config/rules/registry.py` "
        "and `parser_scope.py`. Parser behavior below is documented from the parsers themselves.",
        "",
        "Regenerate:",
        "",
        "```bash",
        "PYTHONPATH=services/orchestrator:services/shift-left-shared \\",
        "  .venv/bin/python scripts/generate_docs.py --platforms",
        "```",
        "",
        "Routing and unclaimed-file behavior: [gate-enforcement.md](gate-enforcement.md). "
        "How to add a rule: [writing-rules.md](writing-rules.md).",
        "",
        "## Undeclared CLI (`CLI-001`)",
        "",
        "A config file with no managed target, and no IOS-XE, NX-OS, or ASA markers, does not "
        "get findings from every platform. The undeclared path emits **CLI-001** (CWE-754, block, "
        "`enforced_prematch`, not waivable). The remedy is declaring a managed target, not a "
        "code change and not a waiver.",
        "",
        "```yaml",
        "managed_targets:",
        "  targets:",
        "    - id: edge-fw-01",
        "      display_name: edge-fw-01",
        "      target_type: cisco_ios_xe",
        "      repo: owner/repo",
        "      branch: main",
        "      config_paths:",
        "        - \"configs/**/*.cfg\"",
        "```",
        "",
        "`target_type` is `cisco_secure_firewall`, `cisco_ios_xe`, or `cisco_nx_os`. "
        "`config_paths` must cover the file. Troubleshooting: [troubleshooting.md](troubleshooting.md).",
        "",
        "| Target type | Typical files | Parser package |",
        "|-------------|---------------|----------------|",
        "| `cisco_secure_firewall` | `*.rules`, `*.conf` | `parsers/asa/` |",
        "| `cisco_ftd` | `*.tf`, `*.hcl` | `parsers/ftd/` |",
        "| `cisco_ios_xe` | `*.cfg`, `*.conf`, `*.txt` | `parsers/ios_xe/` |",
        "| `cisco_nx_os` | `*.cfg`, `*.conf`, `*.txt` | `parsers/nx_os/` |",
        "| `generic_terraform` | `*.tf`, `*.hcl`, `*.tfvars` | `parsers/terraform_hcl.py` |",
        "",
    ]
    for target_type in PLATFORM_ORDER:
        prose = PLATFORM_PROSE[target_type]
        globs = ", ".join(f"`{g}`" for g in TARGET_TYPE_PARSER_GLOBS[target_type])
        lines.extend(
            [
                f"## {prose['title']}",
                "",
                f"**Claimed extensions:** {prose['extensions']} (parser globs: {globs}).",
                "",
                f"**What the parser understands:** {prose['understands']}",
                "",
                f"**Object and group resolution:** {prose['resolve']}",
                "",
                f"**Unparseable content:** {prose['unparsed']}",
                "",
                f"**Not parsed:** {prose['not_parsed']}",
                "",
                "| Rule | CWE | Severity | Status | Description |",
                "|------|-----|----------|--------|-------------|",
            ]
        )
        for rule in _rules_for_platform(target_type):
            desc = " ".join(rule.description.split())
            lines.append(
                f"| `{rule.id}` | {rule.cwe} | {rule.severity} | "
                f"{rule.registry_status} | {desc} |"
            )
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_openapi(path: Path) -> None:
    import importlib.util

    module_path = ROOT / "scripts" / "generate-openapi.py"
    spec = importlib.util.spec_from_file_location("generate_openapi", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {module_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    yaml_path, json_path = module.write_openapi_files(path.parent)
    print(f"wrote {yaml_path.relative_to(ROOT)}")
    print(f"wrote {json_path.relative_to(ROOT)}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--openapi", action="store_true")
    parser.add_argument("--config-ref", action="store_true")
    parser.add_argument("--platforms", action="store_true")
    args = parser.parse_args()
    selected = args.openapi or args.config_ref or args.platforms
    if not selected:
        args.openapi = args.config_ref = args.platforms = True
    docs = ROOT / "docs"
    if args.config_ref:
        write_config_reference(docs / "configuration-reference.md")
        print("wrote docs/configuration-reference.md")
    if args.platforms:
        write_supported_platforms(docs / "supported-platforms.md")
        print("wrote docs/supported-platforms.md")
    if args.openapi:
        write_openapi(docs / "openapi.yaml")


if __name__ == "__main__":
    main()
