#!/usr/bin/env python3
"""Emit docs/openapi.yaml and docs/openapi.json from the FastAPI app.

Do not hand-edit the generated files. Refresh:

    make docs-openapi

or:

    PYTHONPATH=services/orchestrator:services/shift-left-shared \\
      .venv/bin/python scripts/generate-openapi.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ORCH = ROOT / "services" / "orchestrator"
SHARED = ROOT / "services" / "shift-left-shared"
for path in (ORCH, SHARED):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))


YAML_HEADER = (
    "# Generated by scripts/generate-openapi.py from the FastAPI app.\n"
    "# Do not edit by hand.\n"
    "# make docs-openapi\n"
)


def build_spec() -> dict:
    from shift_left.api.route_docs import build_openapi_document
    from shift_left.main import app

    app.openapi_schema = None
    return build_openapi_document(app)


def dump_yaml(spec: dict) -> str:
    import yaml

    return YAML_HEADER + yaml.safe_dump(spec, sort_keys=False, allow_unicode=True)


def dump_json(spec: dict) -> str:
    return json.dumps(spec, indent=2, ensure_ascii=False) + "\n"


def write_openapi_files(docs_dir: Path | None = None) -> tuple[Path, Path]:
    docs = docs_dir or (ROOT / "docs")
    spec = build_spec()
    yaml_path = docs / "openapi.yaml"
    json_path = docs / "openapi.json"
    yaml_path.write_text(dump_yaml(spec), encoding="utf-8")
    json_path.write_text(dump_json(spec), encoding="utf-8")
    return yaml_path, json_path


def main() -> None:
    yaml_path, json_path = write_openapi_files()
    print(f"wrote {yaml_path.relative_to(ROOT)}")
    print(f"wrote {json_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
